### ISSUE TITLE
pse->msvj

### ISSUE THREAD

**Issue by zachcp** [matteoferla/MichelaNGLo-transpiler#1]
Hi @matteoferla ,

I wanted to let you know about [pseutils](https://github.com/zachcp/pseutils), a project I started to teach myself rust.  Right now it is 2 part tool - bits that serialize a PSE bindary to RUST data structures, and then a set of functions to generate [MVSJ files](https://molstar.org/mol-view-spec-docs/mvs-molstar-extension/).  Although I started without knowledge of MichaelaNGLo, I found it when trying to demystify the PSE format. I wanted to let you know in case you still have interest PSE conversion and I'd be particularly interested in your insight on converting the View/Viewport coordinates to MVSJ.

Thanks again for your great code and docs,
zach cp

**Comment by matteoferla** [comment]
The Michelanglo web app is complete and published, so will not change —but thanks for offer!

In terms of the view affine transform matrix, I struggled until I realised I had to flip the sign of the y axis for PyMOL <-> NGL. I blamed it on alibi vs alias rotations, but I never checked whether that is actually the case, or a non-standard notation on behalf of either tool.

**Comment by zachcp** [comment]
Thanks @matteoferla  - Michelanglo is fantastic.
